## Assignment 1 Solutions

1.

a) True as nxn matrices comprises of vectors and vectors are closed under addition and multiplication.

b) False as the plane does not contain the origin and thus it is not closed under addition and multiplication so not a subspace.

c) True as the Linear span of basis vectors spans the 2D Real space.

d) True as the vectors given are not linearily independent so the linear span is a plane.If vectors were linearily independent,then span would be 3D Real space.

e) False as the dimension or the count of elements in the basis set should be 2 as it is spanning 2D Real space but it is more than 2 that is 3 so it will form a set of linearly dependent vectors and thus would not form basis.

f) True as the set of vectors in B have a linear span as 3D Real space and they also are a part of vector space hence its a basis.

g) True as coordinate vector can be found out getting the linear combination of the basis vector and equating it with the given b vector value that is (1,3) so the constants or coefficients we get on solving the linear combination that is x+y=1 and x-y=3 will give (x,y) as (2,-1) that is the desired result.

h) False Here T(x) is defining a norm in 3D real space so for it to be linear functional it should satisfy addition and scalar multiplication property and it fails for the second one as $\|ax \|=|a|\|x \|$ where a is a scalar so here it is taking the modulus value of scalar and also fails on the first one due to triangle inequality property of norm i.e. $\|x+y \|<=\|x \| + \|y \|$

i) True as since $T$ is a linear function, $T(x+y) = T(x)+T(y)$ for all vectors $x$ and $y$.
Also, $(1,0) + (0,1) = (1,1)$  Alternatively, we can find the coefficients or constants for linear combination of given conditions and solve the two equations to get the constants value and plugging it into the equation with desired input,we get the expected output value.

j) False as the dot product of the two vectors is not equal to 0 as 1x1 + -1x1 + 1x1 =1 

2.
a) Creating vectors a and b with initial data and printing output list for 2a-3b

In [2]:
import numpy as np
a=np.array([1,1,0])
b=np.array([0,1,1])
result=2*a-3*b
print(result)

[ 2 -1 -3]


b) Creating new vector c by concatenating a and b vectors

In [6]:
c=np.concatenate([a,b])
print(c)

[1 1 0 0 1 1]


c) Creating vector d=(a2,b2,b3)

In [7]:
d=np.array([a[1],b[1],b[2]])
print(d)

[1 1 1]


d) Calculating Euclidean Distance between a and b vectors

In [8]:
euclideanDistance=np.sqrt(np.sum((a-b)**2))
print(euclideanDistance)

1.4142135623730951


e) Computing the angle between a+b and a-b vectors

In [13]:
p=a+b
q=a-b
input_radians=[]
unit_vector_p= p / np.linalg.norm(p)
unit_vector_q= q / np.linalg.norm(q)
angle_in_radians=np.arccos(np.clip(np.dot(unit_vector_p, unit_vector_q), -1.0, 1.0))
print(angle_in_radians)    # Angle between vectors in Radians
input_radians.append(angle_in_radians)
angle_in_degrees=np.rad2deg(input_radians)
print(angle_in_degrees[0]) # Angle between vectors in Degrees

1.5707963267948966
90.0


3.
a) Create submatrix of given form when A is a symmetric matrix

In [18]:
A = np.random.randint(1,10,size=(3,3))
A_symmetric = (A + A.T)/2  # Generate Random Symmetric Matrix
print(A_symmetric)
A_symmetric_submat=A_symmetric[[0,2]][:,[0,2]] # Generate Submatrix for Symmetric Matrix
print(A_symmetric_submat)

[[6.  6.5 4.5]
 [6.5 3.  7. ]
 [4.5 7.  1. ]]
[[6.  4.5]
 [4.5 1. ]]


b) Create submatrix of given form when A is a skew-symmetric matrix

In [27]:
A = np.random.randint(1,10,size=(3,3))
A_skewsymmetric = (A - A.T)/2  # Generate Random SkewSymmetric Matrix
print(A_skewsymmetric)
A_skewsymmetric_submat=A_skewsymmetric[[0,2]][:,[0,2]] # Generate Submatrix for SkewSymmetric Matrix
print(A_skewsymmetric_submat)

[[ 0.  -1.5 -2. ]
 [ 1.5  0.  -4. ]
 [ 2.   4.   0. ]]
[[ 0. -2.]
 [ 2.  0.]]


c) Create submatrix of given form when A is a stochastic matrix

In [28]:
# Creating Doubly Stochastic Matrix of form [[1-a-b b a][a 1-a-b b][b a 1-a-b]]

A = np.random.randint(1,10,size=(3))
Stochasticmat=np.array([A/A.sum()])
Stochasticmatcol2=np.array([[Stochasticmat[0,2],Stochasticmat[0,0],Stochasticmat[0,1]]])
Stochasticmatcol3=np.array([[Stochasticmat[0,1],Stochasticmat[0,2],Stochasticmat[0,0]]])
DoublyStochasticmat=np.concatenate([Stochasticmat,Stochasticmatcol2,Stochasticmatcol3])
DoublyStochasticmat=DoublyStochasticmat.reshape(3,3)
print(DoublyStochasticmat)
DoublyStochasticmat_submat=DoublyStochasticmat[[0,2]][:,[0,2]] # Generate Submatrix for Doubly stochastic Matrix
print(DoublyStochasticmat_submat)

# Creating Left And Right Stochastic Matrix

A=np.random.rand(3,3)
rightStochasticmat=A/A.sum(axis=1)[:,None]
leftStochasticmat=A/A.sum(axis=0)[None,:]
print(rightStochasticmat) # Right stochastic matrix where row sum is 1
print(leftStochasticmat) # Left stochastic matrix where column sum is 1
A_rightStochastic_submat=rightStochasticmat[[0,2]][:,[0,2]] # Generate Submatrix for Right stochastic Matrix
print(A_rightStochastic_submat)
A_leftStochastic_submat=leftStochasticmat[[0,2]][:,[0,2]] # Generate Submatrix for Left stochastic Matrix
print(A_leftStochastic_submat)

[[0.5   0.375 0.125]
 [0.125 0.5   0.375]
 [0.375 0.125 0.5  ]]
[[0.5   0.125]
 [0.375 0.5  ]]
[[0.36221562 0.51702996 0.12075442]
 [0.82483737 0.15649458 0.01866805]
 [0.10686425 0.49248758 0.40064817]]
[[0.34981157 0.39172194 0.17119917]
 [0.50263558 0.0748134  0.01669996]
 [0.14755285 0.53346466 0.81210087]]
[[0.36221562 0.12075442]
 [0.10686425 0.40064817]]
[[0.34981157 0.17119917]
 [0.14755285 0.81210087]]


d) Create submatrix of given form when A is a Hankel matrix

In [38]:
m=3
n=3
y=np.random.rand(m+n-1)
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = y[i+j]  # Hankel Matrix
print(A)
A_hankel_submat=A[[0,2]][:,[0,2]] # Generate Submatrix for Hankel Matrix
print(A_hankel_submat)

[[0.81673737 0.60162469 0.66535507]
 [0.60162469 0.66535507 0.03791125]
 [0.66535507 0.03791125 0.81503111]]
[[0.81673737 0.66535507]
 [0.66535507 0.81503111]]


4.a) Given dataset find the mean and standard deviation

In [7]:
import numpy as np
A=np.array([[1,-1,0,1,3],[2,3,-1,-4,4],[1,0,1,1,-2]])
A=A.reshape(3,5)
D=A.T
print(A)
print(D)

# With mean and standard deviation formulas
mean=np.sum(A,axis=1)/A.shape[1]
print(mean)
stddev=np.sqrt(np.sum((D-mean)**2,axis=0)/A.shape[1])
print(stddev)

# Computing mean and standard deviation through inbuilt libraries

print(np.mean(A,axis=1))
print(np.std(A,axis=1,dtype=np.float64))

[[ 1 -1  0  1  3]
 [ 2  3 -1 -4  4]
 [ 1  0  1  1 -2]]
[[ 1  2  1]
 [-1  3  0]
 [ 0 -1  1]
 [ 1 -4  1]
 [ 3  4 -2]]
[0.8 0.8 0.2]
[1.32664992 2.92574777 1.16619038]
[0.8 0.8 0.2]
[1.32664992 2.92574777 1.16619038]


b) Nearest Neighbour of point (1,1,1) in DataSet

In [31]:
x=np.array([1,1,1])
min_val=np.finfo(np.float64).max
for i in range(len(D)):
    euclideanDistance=np.sqrt(np.sum((x-D[i])**2)) # euclidean norm taken to compute distance between the coordinates
    if min_val>=euclideanDistance:
        min_val=euclideanDistance
        p=D[i]
p=p.tolist()
print(min_val)
print("Corresponding x,y,z coordinates for DataSet point nearest to (1,1,1) is","("+",".join(map(str, p))+")")

1.0
Corresponding x,y,z coordinates for DataSet point nearest to (1,1,1) is (1,2,1)
