In [13]:
# Question 1
# Create a tensor of shape (2,3)  having normal distribution having mean 4 and std 0.5
# Create a tensor Y of shape (2,3) having a sequence of numbers 12,15,18,...., 150
# Get and Print sum of these two Tensors that is Z=  X+Y   (Shape of Z would be same as that of X or Y)
# For tensor Y it has sequence of size 47 and nearest greatest shape is 48 so the unfilled element is assumed to be the last sequence element

import tensorflow as tf
import numpy as np
X=tf.random.truncated_normal(
    [2,3],
    mean=4.0,
    stddev=0.5,
    dtype=tf.dtypes.float32)
Y=tf.constant(np.arange(12,153,3),dtype=tf.dtypes.float32,shape=[8,2,3])
#sequence_tensor_reshaped=tf.reshape(sequence_tensor,[-1,2,3])
Z=tf.add(X,Y)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(X))
    print(sess.run(Y))
    print(sess.run(Z))
sess.close()
tf.reset_default_graph()

[[3.049821  3.5824244 3.4151907]
 [3.9007828 4.30029   3.5557146]]
[[[ 12.  15.  18.]
  [ 21.  24.  27.]]

 [[ 30.  33.  36.]
  [ 39.  42.  45.]]

 [[ 48.  51.  54.]
  [ 57.  60.  63.]]

 [[ 66.  69.  72.]
  [ 75.  78.  81.]]

 [[ 84.  87.  90.]
  [ 93.  96.  99.]]

 [[102. 105. 108.]
  [111. 114. 117.]]

 [[120. 123. 126.]
  [129. 132. 135.]]

 [[138. 141. 144.]
  [147. 150. 150.]]]
[[[ 16.173452  18.817461  22.354378]
  [ 24.55879   27.982918  30.451134]]

 [[ 34.17345   36.81746   40.354378]
  [ 42.55879   45.982918  48.451134]]

 [[ 52.17345   54.81746   58.354378]
  [ 60.55879   63.982918  66.45113 ]]

 [[ 70.173454  72.81746   76.35438 ]
  [ 78.55879   81.98292   84.45113 ]]

 [[ 88.173454  90.81746   94.35438 ]
  [ 96.55879   99.98292  102.45113 ]]

 [[106.173454 108.81746  112.35438 ]
  [114.55879  117.98292  120.45113 ]]

 [[124.173454 126.81746  130.35439 ]
  [132.55879  135.98291  138.45114 ]]

 [[142.17345  144.81746  148.35439 ]
  [150.55879  153.98291  153.45114 ]]]


In [19]:
# Question 2
#Get a new tensor W = tanh(Z)
#Get a new tensor T= sigmoid(Z)
import tensorflow as tf
import numpy as np
X=tf.random.truncated_normal(
    [2,3],
    mean=4.0,
    stddev=0.5,
    dtype=tf.dtypes.float32)
Y=tf.constant(np.arange(12,153,3),dtype=tf.dtypes.float32,shape=[8,2,3])
#sequence_tensor_reshaped=tf.reshape(sequence_tensor,[-1,2,3])
Z=tf.add(X,Y)
T=tf.nn.sigmoid(Z)
W=tf.nn.tanh(Z)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(W))
    print(sess.run(T))
sess.close()
tf.reset_default_graph()

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[0.99999976 1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]]


In [20]:
## Question 3
# Replacing sigmoid/tanh with another(new) activation function that is ( exp^(f) - exp^(-f) )/( exp^(f) + exp^(-f) ) + (1 / ( 1 + exp^(-f) ))
import tensorflow as tf
W = tf.random_normal(shape=(3,2))
X = tf.constant([2,4], dtype=tf.float32)
B = tf.zeros(shape=(2))
f = W*X + B
newActivationResult = ((tf.exp(f) - tf.exp(-f)) / (tf.exp(f) + tf.exp(-f))) + (1 / ( 1 + tf.exp(-f)))
with tf.Session() as sess:
    output = sess.run(newActivationResult)
    print(output)


#If we want to replace new activation function with sigmoid, which line is to be changed? 

# The line with newActiation Result has to be changed. The below code is edited in the next cell.

[[-0.88930625  1.998198  ]
 [ 1.862628    1.9984633 ]
 [-0.9619495   1.8860018 ]]


In [21]:
import tensorflow as tf
W = tf.random_normal(shape=(3,2))
X = tf.constant([2,4], dtype=tf.float32)
B = tf.zeros(shape=(2))
f = W*X + B
newActivationResult = tf.nn.sigmoid(f)
with tf.Session() as sess:
    output = sess.run(newActivationResult)
    print(output)

[[0.54479337 0.00580677]
 [0.20767331 0.9694786 ]
 [0.7611827  0.96055   ]]


In [22]:
# Question 4
import tensorflow as tf
import numpy as np
inp = tf.placeholder(shape=(1, 32, 32, 3), dtype=tf.float32)
output = 2*inp + 5
with tf.Session() as sess:
    network_input = np.random.randint(5,  size=(256, 3))
    network_input = np.resize(network_input, (1, 32,32, 3))
    out = sess.run(output, feed_dict = {inp: network_input})
    print(out)
    
    
 # Please describe the steps in 3 lines

# Answer
#The network input has random integers starting from atleast 5 with original size as 256x3
#The placeholder size is 1x32x32x3 so the network input is resized into 1x32x32x3
#The output is scalar multiplication and addition with respect to network input so dimensions are same as network input i.e. 1x32x32x3

[[[[13.  5.  7.]
   [13. 13.  9.]
   [ 9. 13.  5.]
   ...
   [ 9.  5. 13.]
   [13. 13.  9.]
   [ 5.  5. 11.]]

  [[11. 13. 13.]
   [ 7.  5.  7.]
   [ 9.  7.  5.]
   ...
   [13.  5.  5.]
   [ 7.  7.  7.]
   [ 7. 13. 11.]]

  [[ 7.  7.  9.]
   [11. 11. 13.]
   [ 5.  7. 13.]
   ...
   [13. 13. 13.]
   [ 5. 11. 11.]
   [ 5.  9. 13.]]

  ...

  [[ 5.  9. 11.]
   [ 5. 13.  9.]
   [ 7.  7. 11.]
   ...
   [11.  9. 13.]
   [11.  9.  7.]
   [ 9. 11. 11.]]

  [[ 7. 11.  5.]
   [11.  5.  7.]
   [ 5.  7. 13.]
   ...
   [ 5.  5. 13.]
   [11.  5.  7.]
   [13.  7. 13.]]

  [[ 9. 13.  9.]
   [ 9. 13. 11.]
   [ 9.  9.  5.]
   ...
   [11.  5.  7.]
   [13. 11.  7.]
   [13.  5. 11.]]]]


In [ ]:
# Question 5
# Build an image(digit) classifier using keras for MNIST data using adagrad, 'binary_crossentropy' using MLP (not CNN)

# The MLP model is defined below

In [23]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import np_utils
(xtrain, ytrain), (xtest, ytest) = mnist.load_data()
num_pixels = xtrain.shape[1] * xtrain.shape[2]
xtrain = xtrain.reshape(xtrain.shape[0], num_pixels).astype('float32')
xtest = xtest.reshape(xtest.shape[0], num_pixels).astype('float32')
xtrain = xtrain / 255
xtest = xtest / 255
ytrain = np_utils.to_categorical(ytrain)
ytest = np_utils.to_categorical(ytest)
num_classes = ytest.shape[1]
model = Sequential()
model.add(Dense(num_pixels, input_dim=num_pixels, kernel_initializer='normal', activation='relu'))
model.add(Dense(num_classes, kernel_initializer='normal', activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adagrad', metrics=['accuracy'])
model.fit(xtrain, ytrain, validation_data=(xtest, ytest), epochs=10, batch_size=200, verbose=2)
scores = model.evaluate(xtest, ytest, verbose=0)
print("Error: %.2f%%" % (100-scores[1]*100))

Using TensorFlow backend.
W0717 20:02:36.506525 140493467207488 deprecation_wrapper.py:119] From /opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0717 20:02:36.508580 140493467207488 deprecation_wrapper.py:119] From /opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0717 20:02:36.511847 140493467207488 deprecation_wrapper.py:119] From /opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4115: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0717 20:02:36.533162 140493467207488 deprecation_wrapper.py:119] From /opt/anaconda3/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0717 20:02:36.6

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 3s - loss: 0.0438 - acc: 0.9861 - val_loss: 0.0235 - val_acc: 0.9921
Epoch 2/10
 - 3s - loss: 0.0201 - acc: 0.9936 - val_loss: 0.0183 - val_acc: 0.9938
Epoch 3/10
 - 3s - loss: 0.0153 - acc: 0.9954 - val_loss: 0.0167 - val_acc: 0.9947
Epoch 4/10
 - 3s - loss: 0.0126 - acc: 0.9962 - val_loss: 0.0148 - val_acc: 0.9950
Epoch 5/10
 - 3s - loss: 0.0106 - acc: 0.9969 - val_loss: 0.0139 - val_acc: 0.9952
Epoch 6/10
 - 3s - loss: 0.0093 - acc: 0.9974 - val_loss: 0.0133 - val_acc: 0.9956
Epoch 7/10
 - 3s - loss: 0.0082 - acc: 0.9978 - val_loss: 0.0125 - val_acc: 0.9957
Epoch 8/10
 - 2s - loss: 0.0073 - acc: 0.9981 - val_loss: 0.0125 - val_acc: 0.9959
Epoch 9/10
 - 2s - loss: 0.0065 - acc: 0.9983 - val_loss: 0.0119 - val_acc: 0.9958
Epoch 10/10
 - 2s - loss: 0.0059 - acc: 0.9985 - val_loss: 0.0116 - val_acc: 0.9960
Error: 0.40%
